schema_version = "1.0.0"

id = "thebetterbaker"
version = "4.0.0"
name = "The Better Baker - PBR Baker"
tagline = "A PBR baker for multiple objects and complex materials"
maintainer = "Chaim Mendes"
type = "add-on"

website = "https://thebetterbaker.github.io/"

# # https://docs.blender.org/manual/en/dev/advanced/extensions/tags.html
tags = ["Bake", "Game Engine", "Paint"]

blender_version_min = "5.1.0"

# Max Currently Unknown
# tested variants
# ->5.1
# ->5.2 LTS
# blender_version_max = "X.X.X"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = [
  "SPDX:GPL-3.0-or-later",
]

# to zip (In Windows) run
# & "C:\Program Files\Blender Foundation\Blender 5.2\blender.exe" --command extension build --source .

paths_exclude_pattern = [
  "__pycache__/",
  "/.git/",
  "/*.zip",
  "/.gitignore",
]